version: '2'
services:
  vanilla:
    build: vanilla/
    container_name: vanilla
    volumes:
      - ./vanilla/top-output.txt:/top-output.txt
  vanilla-handler:
    build: vanilla-handler/
    container_name: vanilla-handler
    volumes:
      - ./vanilla-handler/top-output.txt:/top-output.txt
  docker:
    build: docker/
    container_name: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/top-output.txt:/top-output.txt
  modified-agent:
    build: agent/
    container_name: modified-agent
    environment:
      - APIKEY=<api-key>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  agent-rc:
    build: agent-rc/
    container_name: agent-rc
    environment:
      - APIKEY=<api-key>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  agent:
    image: netuitive/docker-agent
    container_name: agent
    environment:
      - APIKEY=<api-key>
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  docker-generator:
    build: docker-generator/
    container_name: generator
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
